openapi: 3.0.1
info:
  title: Pagopa payment gateway Mock
  version: '1.0.0'
tags:
  - name: paypalmock
    description: todo
  - name: paypalmanagement
    description: todo
paths:
  /paypalpsp/api/pp_onboarding_back:
    post:
      tags:
        - paypalmock
      summary: server to server api used to start onboarding
      requestBody:
        description: New Onboarding required
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StartOnboardingRequest'

      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/StartOnboardingResponseSuccess'
                  - $ref: '#/components/schemas/StartOnboardingResponseError'
      security:
        - bearerAuth: []
  /postepay/api/v1/payment/create:
    post:
      operationId: createPayment
      tags:
      - Payment Manager Controller
      summary: Inzializzazione della transazione di pagamento
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePaymentRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                description: ""
                required:
                - paymentID
                - userRedirectURL
                type: object
                properties:
                  paymentID:
                    description: identificativo della transazione di pagamento assegnato
                      da PosteItaliane
                    type: string
                  userRedirectURL:
                    description: URL verso cui redirigere l'utente per portare a compimento
                      la transazione
                    type: string
        default:
          description: Errore
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostePayError'
  /postepay/api/v1/user/onboarding:
    post:
      operationId: userPostepayOnboarding
      summary: Postepay user onboarding
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OnboardingPostepayRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                description: ""
                required:
                - onboardingID
                - userRedirectURL
                type: object
                properties:
                  onboardingID:
                    description: identificativo della transazione di pagamento assegnato
                      da PosteItaliane
                    type: string
                  userRedirectURL:
                    description: URL verso cui redirigere l'utente per portare a compimento
                      la transazione
                    type: string
        default:
          description: Errore
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostePayError'
  /postepayweb/change/outcome:
    post:
      operationId: changeOutcomePostePay
      tags:
      - Payment Manager Controller
      parameters:
        - in: query
          name: paymentOutcome
          schema:
            type: string
        - in: query
          name: timeoutMs
          schema:
            type: integer
      responses:
        "200":
          description: OK
  /postepay/api/v1/payment/details:
    post:
      operationId: paymentDetail
      summary: Dettagli di una transazione di pagamento
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeatilsPaymentRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                description: ""
                required:
                - paymentID
                - userRedirectURL
                - shopId;
                - shopTransactionId
                - result
                - authNumber
                - amount
                - description
                - currency
                - buyerName
                - buyerEmail
                - paymentChannel
                - authType
                - status
                - refundedAmount
                type: object
                properties:
                  paymentID:
                    type: string
                  userRedirectURL:
                    type: string
                  shopId:
                    type: string
                  shopTransactionId:
                    type: string
                  result:
                    type: string
                  authNumber:
                    type: string
                  amount:
                    type: string
                  description:
                    type: string
                  currency:
                    type: string
                  buyerName:
                    type: string
                  buyerEmail:
                   type: string
                  paymentChannel:
                    type: string
                  authType:
                    type: string
                  status:
                    type: string
                  refundedAmount:
                    type: string  
        default:
          description: Errore
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostePayError'
  /postepay/api/v1/payment/refund:
    post:
      operationId: refundPostepayPayment
      tags:
      - Payment Manager Controller
      summary: refund transazione di pagamento
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefundPaymentRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                description: ""
                required:
                - paymentID
                - shopTransactionId
                - transactionResult
                type: object
                properties:
                  paymentID:
                    description: identificativo della transazione di pagamento assegnato
                      da PosteItaliane
                    type: string
                  shopTransactionId:
                    type: string
                  transactionResult:
                    type: string
                    enum:
                    - OK
                    - KO
        default:
          description: Errore
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostePayError'
                
components:
  schemas:
    PostePayError:
      type: object
      properties:
        errorCode:
          description: Codice di errore
          type: string
        description:
          description: Descrizione tecnica dell'errore
          type: string
        message:
          description: Messaggio utente
          type: string
    StartOnboardingRequest:
      required:
        - url_return
        - id_appio
      type: object
      properties:
        url_return:
          type: string
          description: URL used to return the result
        id_appio:
          type: string
          description: user identifier
    StartOnboardingResponseSuccess:
      required:
        - esito
        - url_to_call
      type: object
      properties:
        esito:
          type: string
          enum:
            - "1"
          description: URL used to return the result
        url_to_call:
          type: string
          description: url to call to proceed with onboarding
    StartOnboardingResponseError:
      required:
        - esito
        - err_code
        - err_desc
      type: object
      properties:
        esito:
          type: string
          enum:
            - "3" #cancel by user
            - "9" #error
          description: Api result
        err_code:
          type: string
          enum:
            - "9" #input non in formato json
            - "11" #parametri non validi
            - "13" #autorizzazione negata
            - "15" #autorizzazione ip negata
            - "19" #id_appio con bilagr già associato
            - "67" #db internal error
        err_desc:
          type: string
    AuthorizationType:
      enum:
      - IMMEDIATA
      - DIFFERITA
      type: string
    DeatilsPaymentRequest:
      description: ""
      required:
      - shopId
      - shopTransactionId
      - paymentID
      type: object
      properties:
        shopId:
          description: identificativo del negozio
          type: string
        shopTransactionId:
          description: identificativo della transazione lato merchant
          type: string
        paymentID:
          description: paymentID
          type: string
    OnboardingPostepayRequest:
      description: ""
      required:
      - shopId
      - merchantId
      - onboardingTransactionId
      - paymentChannel
      - responseURLs
      type: object
      properties:
        shopId:
          description: identificativo del negozio
          type: string
        merchantId:
          description: identificativo del merchant
          type: string
        onboardingTransactionId:
          description: id onboarding transaction Id
          type: string
        paymentChannel:
          allOf:
          - $ref: '#/components/schemas/PaymentChannel'
          - description: "canale di pagamento, puo essere valorizzato con APP/WEB"
        responseURLs:
          allOf:
          - $ref: '#/components/schemas/ResponseURLs'
          - description: URL di ritorno
    CreatePaymentRequest:
      description: ""
      required:
      - shopId
      - shopTransactionId
      - amount
      - currency
      - paymentChannel
      - authType
      - responseURLs
      type: object
      properties:
        shopId:
          description: identificativo del negozio
          type: string
        shopTransactionId:
          description: identificativo della transazione lato merchant
          type: string
        amount:
          description: importo
          type: string
        description:
          description: descrizione della transazione presentata al cliente
          type: string
        currency:
          description: valuta in codice ISO (EUR = 978)
          type: string
        buyerName:
          description: nome del cliente
          type: string
        buyerEmail:
          description: indirizzo email del cliente
          type: string
        paymentChannel:
          allOf:
          - $ref: '#/components/schemas/PaymentChannel'
          - description: "canale di pagamento, puo essere valorizzato con APP/WEB"
        authType:
          allOf:
          - $ref: '#/components/schemas/AuthorizationType'
          - description: "tipo di autorizzazione, puo essere valorizzato con IMMEDIATA/DIFFERITA"
        responseURLs:
          allOf:
          - $ref: '#/components/schemas/ResponseURLs'
          - description: URL di ritorno
    RefundPaymentRequest:
      description: ""
      required:
      - shopId
      - shopTransactionId
      - merchantId
      - paymentID
      - authNumber
      - currency
      type: object
      properties:
        shopId:
          description: identificativo del negozio
          type: string
        shopTransactionId:
          description: identificativo della transazione lato merchant
          type: string
        amount:
          description: importo
          type: string
        reason:
          description: descrizione della transazione presentata al cliente
          type: string
        currency:
          description: valuta in codice ISO (EUR = 978)
          type: string
        merchantId:
          type: string
        paymentID:
          type: string
        authNumber:
          type: string
    PaymentChannel:
      enum:
      - WEB
      - APP
      type: string
    ResponseURLs:
      description: ""
      required:
      - responseUrlOk
      - responseUrlKo
      - serverNotificationUrl
      type: object
      properties:
        responseUrlOk:
          description: URL di redirect dell'utente per transazione OK completa di
            eventuali parametri da passare
          type: string
        responseUrlKo:
          description: URL di redirect dell'utente per transazione KO completa di
            eventuali parametri da passare
          type: string
        serverNotificationUrl:
          description: URL presso la quale sarà eseguita la chiamata di conferma del
            pagamento solo per i casi OK
          type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: string
