spring:
  application:
    name: Payment Manager Mock PSP
  datasource:
    platform: postgres
    url: jdbc:postgresql://${PAGOPA_MOCK_PSP_DB_URL:localhost:5432/pm_mock_local}
    driverClassName: org.postgresql.Driver
    username: ${PAGOPA_MOCK_PSP_DB_USERNAME:pm_mock_local}
    password: ${PAGOPA_MOCK_PSP_DB_PWD:pm_mock_local}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mvc:
    static-path-pattern: /static/**
  endpoints:
    web:
      exposure:
        include: "info,health,prometheus"

server:
  port: ${SERVER_PORT:7954}
  public-url: ${SERVER_PUBLIC_URL:http://localhost:${server.port}}
#  azure-api-static-res: ${AZURE_API_STATIC_RES:/}

logging:
  level:
    root: INFO
    org:
      zalando:
        logbook: TRACE

logbook:
  include:
    - /paypalpsp/**
  obfuscate:
    headers:
      - None