apiVersion: apps/v1
kind: Deployment
metadata:
  name: pagopapmcloudmock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pagopapmcloudmock
  template:
    metadata:
      labels:
        app: pagopapmcloudmock
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: '8080'
        prometheus.io/scrape: 'true'
    spec:
      containers:
        - name: pagopapmcloudmock
          image: cstaruatregistry.azurecr.io/pagopapmcloudmock
          ports:
            - containerPort: 8080
#          envFrom:
#            - secretRef:
#                name: keyvault-connection-informations
#            - configMapRef:
#                name: kafka-log-configuration
#            - configMapRef:
#                name: tkmmscardmanager
#            - configMapRef:
#                name: jvm
          resources:
            limits:
              cpu: 1000m
              memory: 4Gi
            requests:
              cpu: 50m
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 30
          imagePullPolicy: Always
