# Upgrades the version numbers as reported in pom files

parameters:
  # Versioning parameters
  - name: 'semver'
    type: string
    values:
    - major
    - minor
    - patch
  - name: 'subproject'
    type: string

steps:
  - ${{ if eq(parameters.semver, 'patch') }}:
    - task: Maven@3
      inputs:
        mavenPomFile: "${{parameters.subproject}}/pom.xml"
        goals: 'build-helper:parse-version versions:set'
        options: '-DnewVersion=${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.nextIncrementalVersion}'