apiVersion: apps/v1
kind: Deployment
metadata:
  name: mockpaymentgatewaysit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mockpaymentgatewaysit
  template:
    metadata:
      labels:
        app: mockpaymentgatewaysit
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: '8081'
        prometheus.io/scrape: 'true'
    spec:
      containers:
        - name: mockpaymentgatewaysit
          image: cstaruatregistry.azurecr.io/mockpaymentgateway
          ports:
            - containerPort: 8081
          resources:
            requests:
              memory: 1Gi
              cpu: 250m
            limits:
              memory: 4Gi
              cpu: 500m
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
              scheme: HTTP
            timeoutSeconds: 5
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
              scheme: HTTP
            timeoutSeconds: 5
            periodSeconds: 45
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 45
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 30
          imagePullPolicy: Always
