//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.26 at 09:55:13 AM CET 
//


package it.gft.p2b.srv.pp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for baseRequestVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="baseRequestVO">
 *   &lt;complexContent>
 *     &lt;extension base="{http://p2b.gft.it/srv/pp}baseRequestLightVO">
 *       &lt;sequence>
 *         &lt;element name="otpContesto" type="{http://p2b.gft.it/srv/pp}otpContestoVO" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "baseRequestVO", propOrder = {
    "otpContesto"
})
@XmlSeeAlso({
    RequestInserimentoRichiestaPagamentoPagoPaVO.class,
    RequestStornoPagamentoVO.class,
    RequestInquiryTransactionStatusVO.class
})
public class BaseRequestVO
    extends BaseRequestLightVO
{

    protected OtpContestoVO otpContesto;

    /**
     * Gets the value of the otpContesto property.
     * 
     * @return
     *     possible object is
     *     {@link OtpContestoVO }
     *     
     */
    public OtpContestoVO getOtpContesto() {
        return otpContesto;
    }

    /**
     * Sets the value of the otpContesto property.
     * 
     * @param value
     *     allowed object is
     *     {@link OtpContestoVO }
     *     
     */
    public void setOtpContesto(OtpContestoVO value) {
        this.otpContesto = value;
    }

}
