//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.26 at 09:55:13 AM CET 
//


package it.gft.p2b.srv.pp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for baseVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="baseVO">
 *   &lt;complexContent>
 *     &lt;extension base="{http://p2b.gft.it/srv/pp}p2BAbstractPresentationBean">
 *       &lt;sequence>
 *         &lt;element name="contesto" type="{http://p2b.gft.it/srv/pp}contestoVO"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "baseVO", propOrder = {
    "contesto"
})
@XmlSeeAlso({
    BaseResponseVO.class,
    BaseRequestLightVO.class
})
public class BaseVO
    extends P2BAbstractPresentationBean
{

    @XmlElement(required = true)
    protected ContestoVO contesto;

    /**
     * Gets the value of the contesto property.
     * 
     * @return
     *     possible object is
     *     {@link ContestoVO }
     *     
     */
    public ContestoVO getContesto() {
        return contesto;
    }

    /**
     * Sets the value of the contesto property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContestoVO }
     *     
     */
    public void setContesto(ContestoVO value) {
        this.contesto = value;
    }

}
