//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.26 at 09:55:13 AM CET 
//


package it.gft.p2b.srv.pp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for otpContestoVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="otpContestoVO">
 *   &lt;complexContent>
 *     &lt;extension base="{http://p2b.gft.it/srv/pp}p2BAbstractPresentationBean">
 *       &lt;sequence>
 *         &lt;element name="deviceIdData" type="{http://p2b.gft.it/srv/pp}deviceIdDataVO" minOccurs="0"/>
 *         &lt;element name="otpData" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="signatureData" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="signatureDataHash" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="transactionId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "otpContestoVO", propOrder = {
    "deviceIdData",
    "otpData",
    "signatureData",
    "signatureDataHash",
    "transactionId"
})
public class OtpContestoVO
    extends P2BAbstractPresentationBean
{

    protected DeviceIdDataVO deviceIdData;
    protected String otpData;
    protected String signatureData;
    protected String signatureDataHash;
    protected long transactionId;

    /**
     * Gets the value of the deviceIdData property.
     * 
     * @return
     *     possible object is
     *     {@link DeviceIdDataVO }
     *     
     */
    public DeviceIdDataVO getDeviceIdData() {
        return deviceIdData;
    }

    /**
     * Sets the value of the deviceIdData property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeviceIdDataVO }
     *     
     */
    public void setDeviceIdData(DeviceIdDataVO value) {
        this.deviceIdData = value;
    }

    /**
     * Gets the value of the otpData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtpData() {
        return otpData;
    }

    /**
     * Sets the value of the otpData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtpData(String value) {
        this.otpData = value;
    }

    /**
     * Gets the value of the signatureData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignatureData() {
        return signatureData;
    }

    /**
     * Sets the value of the signatureData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignatureData(String value) {
        this.signatureData = value;
    }

    /**
     * Gets the value of the signatureDataHash property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignatureDataHash() {
        return signatureDataHash;
    }

    /**
     * Sets the value of the signatureDataHash property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignatureDataHash(String value) {
        this.signatureDataHash = value;
    }

    /**
     * Gets the value of the transactionId property.
     * 
     */
    public long getTransactionId() {
        return transactionId;
    }

    /**
     * Sets the value of the transactionId property.
     * 
     */
    public void setTransactionId(long value) {
        this.transactionId = value;
    }

}
