//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.26 at 09:55:13 AM CET 
//


package it.gft.p2b.srv.pp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for requestInserimentoRichiestaPagamentoPagoPaVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="requestInserimentoRichiestaPagamentoPagoPaVO">
 *   &lt;complexContent>
 *     &lt;extension base="{http://p2b.gft.it/srv/pp}baseRequestVO">
 *       &lt;sequence>
 *         &lt;element name="richiestaPagamentoPagoPa" type="{http://p2b.gft.it/srv/pp}richiestaPagamentoPagoPaVO" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "requestInserimentoRichiestaPagamentoPagoPaVO", propOrder = {
    "richiestaPagamentoPagoPa"
})
public class RequestInserimentoRichiestaPagamentoPagoPaVO
    extends BaseRequestVO
{

    protected RichiestaPagamentoPagoPaVO richiestaPagamentoPagoPa;

    /**
     * Gets the value of the richiestaPagamentoPagoPa property.
     * 
     * @return
     *     possible object is
     *     {@link RichiestaPagamentoPagoPaVO }
     *     
     */
    public RichiestaPagamentoPagoPaVO getRichiestaPagamentoPagoPa() {
        return richiestaPagamentoPagoPa;
    }

    /**
     * Sets the value of the richiestaPagamentoPagoPa property.
     * 
     * @param value
     *     allowed object is
     *     {@link RichiestaPagamentoPagoPaVO }
     *     
     */
    public void setRichiestaPagamentoPagoPa(RichiestaPagamentoPagoPaVO value) {
        this.richiestaPagamentoPagoPa = value;
    }

}
