//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.26 at 09:55:13 AM CET 
//


package it.gft.p2b.srv.pp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for utenteAttivoVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="utenteAttivoVO">
 *   &lt;complexContent>
 *     &lt;extension base="{http://p2b.gft.it/srv/pp}utenteVO">
 *       &lt;sequence>
 *         &lt;element name="deviceUniqueID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="tokenNotifiche" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "utenteAttivoVO", propOrder = {
    "deviceUniqueID",
    "tokenNotifiche"
})
public class UtenteAttivoVO
    extends UtenteVO
{

    protected String deviceUniqueID;
    protected String tokenNotifiche;

    /**
     * Gets the value of the deviceUniqueID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeviceUniqueID() {
        return deviceUniqueID;
    }

    /**
     * Sets the value of the deviceUniqueID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeviceUniqueID(String value) {
        this.deviceUniqueID = value;
    }

    /**
     * Gets the value of the tokenNotifiche property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTokenNotifiche() {
        return tokenNotifiche;
    }

    /**
     * Sets the value of the tokenNotifiche property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTokenNotifiche(String value) {
        this.tokenNotifiche = value;
    }

}
